Replace pydocstyle with ruff
> The Pydocstyle project is officially deprecated, and it is no longer
> actively maintained.

The maintainers recommend ruff as a replacement.  Also see
https://github.com/PyCQA/pydocstyle#deprecation-notice-pydocstyle .

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -80,7 +80,7 @@ find_command() {
 }
 
 DASH=$(find_command dash)
-PYDOCSTYLE=$(find_command pydocstyle)
+RUFF=$(find_command ruff)
 PYFLAKES=$(find_command pyflakes)
 PYCODESTYLE=$(find_command pycodestyle pep8)
 RUBY=$(find_command ruby)
@@ -91,8 +91,8 @@ if [ "$PY_FILES $PY_TEST_FILES" != " " ]; then
 	err "pyflakes tests failed!"
     fi
     # ignore vendored files
-    if ! $PYDOCSTYLE --match='(?!apksigcopier|looseversion).*\.py' $PY_FILES $PY_TEST_FILES; then
-	err "pydocstyle tests failed!"
+    if ! $RUFF check fdroidserver --extend-exclude 'apksigcopier.py,common.py,deploy.py,exception.py,gpgsign.py,index.py,__init__.py,init.py,install.py,lint.py,__main__.py,metadata.py,mirror.py,net.py,publish.py,readmeta.py,rewritemeta.py,scanner.py,signatures.py,signindex.py,tail.py,update.py,verify.py,vmtools.py'; then
+	err "ruff tests failed!"
     fi
 fi
 
